export const GET_EMERGENCY_LEVEL = 'GET_EMERGENCY_LEVEL';
export const CLEAR_LEVEL = 'CLEAR_LEVEL';
export const GET_LEVEL_ERROR = 'GET_LEVEL_ERROR';
export const GET_INTEREST_LEVEL = 'GET_INTEREST_LEVEL';
export const GET_SAVING_LEVEL = 'GET_SAVING_LEVEL';
export const GET_FINANCE_REPORT = 'GET_FINANCE_REPORT';
